In [9]:
import numpy as np

def add_matrices(matrix1, matrix2):
    return np.add(matrix1, matrix2)

def subtract_matrices(matrix1, matrix2):
    return np.subtract(matrix1, matrix2)

def multiply_matrices(matrix1, matrix2):
    return np.matmul(matrix1, matrix2)

def transpose_matrix(matrix):
    return np.transpose(matrix)

def get_matrix_input(matrix_num):
    rows = int(input(f"Enter the number of rows for matrix {matrix_num}: "))
    cols = int(input(f"Enter the number of columns for matrix {matrix_num}: "))
    matrix = []
    for i in range(rows):
        row = list(map(float, input(f"Enter row {i + 1} (space-separated values): ").split()))
        if len(row) != cols:
            raise ValueError("Number of columns does not match the specified size.")
        matrix.append(row)
    return np.array(matrix)

def main():
    print("Matrix Operations using NumPy")
    
    matrix1 = get_matrix_input(1)
    matrix2 = get_matrix_input(2)
    
    print("Matrix 1:")
    print(matrix1)
    
    print("Matrix 2:")
    print(matrix2)
    
    print("\nChoose an operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Transpose Matrix 1")
    print("5. Transpose Matrix 2")
    
    choice = int(input("Enter the number of your choice: "))
    
    if choice == 1:
        if matrix1.shape != matrix2.shape:
            print("Error: Matrices must have the same dimensions to add.")
        else:
            result = add_matrices(matrix1, matrix2)
            print("\nResult of Addition:")
            print(result)
    elif choice == 2:
        if matrix1.shape != matrix2.shape:
            print("Error: Matrices must have the same dimensions to subtract.")
        else:
            result = subtract_matrices(matrix1, matrix2)
            print("\nResult of Subtraction:")
            print(result)
    elif choice == 3:
        if matrix1.shape[1] != matrix2.shape[0]:
            print("Error: Number of columns in Matrix 1 must be equal to number of rows in Matrix 2 to multiply.")
        else:
            result = multiply_matrices(matrix1, matrix2)
            print("\nResult of Multiplication:")
            print(result)
    elif choice == 4:
        result = transpose_matrix(matrix1)
        print("\nTranspose of Matrix 1:")
        print(result)
    elif choice == 5:
        result = transpose_matrix(matrix2)
        print("\nTranspose of Matrix 2:")
        print(result)
    else:
        print("Invalid choice.")

if __name__ == "__main__":
    main()


Matrix Operations using NumPy
Enter the number of rows for matrix 1: 2
Enter the number of columns for matrix 1: 2
Enter row 1 (space-separated values): 1 2
Enter row 2 (space-separated values): 2 3
Enter the number of rows for matrix 2: 2
Enter the number of columns for matrix 2: 2
Enter row 1 (space-separated values): 3 4
Enter row 2 (space-separated values): 4 5
Matrix 1:
[[1. 2.]
 [2. 3.]]
Matrix 2:
[[3. 4.]
 [4. 5.]]

Choose an operation:
1. Add
2. Subtract
3. Multiply
4. Transpose Matrix 1
5. Transpose Matrix 2
Enter the number of your choice: 3

Result of Multiplication:
[[11. 14.]
 [18. 23.]]


# bubble sort


In [11]:
from array import *
x = array('i',[])
print("Enter number of Elements")
n = int(input())
for i in range(n):
    print("Enter a element")
    x.append(int(input()))
print("original array is",x)
for i in range(n-1):
    for j in range(n-1-i):
        if(x[j] > x[j+1]):
            t = x[j]
            x[j] = x[j+ 1]
            x[ j + 1] = t
print("after sorting array is",x)

Enter number of Elements
5
Enter a element
20
Enter a element
25
Enter a element
40
Enter a element
1
Enter a element
5
original array is array('i', [20, 25, 40, 1, 5])
after sorting array is array('i', [1, 5, 20, 25, 40])


# insertion sort


In [13]:
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr
print(insertion_sort([2,20,45,1,12]))

[1, 2, 12, 20, 45]


# Merge Sort


In [15]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        left_half = arr[:mid]
        right_half = arr[mid:]

        merge_sort(left_half)
        merge_sort(right_half)

        i = j = k = 0
        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1

        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1

        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1

    return arr
print(merge_sort([2,20,45,1,12]))

[1, 2, 12, 20, 45]


# Quick sort

In [16]:
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)
print(quick_sort([2,20,45,1,12]))

[1, 2, 12, 20, 45]


# linked list

In [17]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

In [18]:
class LinkedList:
    def __init__(self):
        self.head = None

    def insert(self, data):
        new_node = Node(data)
        new_node.next = self.head
        self.head = new_node

    def delete(self, key):
        temp = self.head

        if temp is not None:
            if temp.data == key:
                self.head = temp.next
                temp = None
                return

        while temp is not None:
            if temp.data == key:
                break
            prev = temp
            temp = temp.next

        if temp == None:
            return

        prev.next = temp.next
        temp = None

    def traverse(self):
        temp = self.head
        while temp:
            print(temp.data, end=' ')
            temp = temp.next
        print()


# stack and queues

In [19]:
class Stack:
    def __init__(self):
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if self.is_empty():
            raise IndexError("pop from empty stack")
        return self.items.pop()

    def peek(self):
        if self.is_empty():
            raise IndexError("peek from empty stack")
        return self.items[-1]

    def size(self):
        return len(self.items)


In [20]:
class Queue:
    def __init__(self):
        self.items = []

    def is_empty(self):
        return len(self.items) == 0

    def enqueue(self, item):
        self.items.append(item)

    def dequeue(self):
        if self.is_empty():
            raise IndexError("dequeue from empty queue")
        return self.items.pop(0)

    def size(self):
        return len(self.items)


In [22]:
if __name__ == "__main__":
    # Sorting examples
    arr = [64, 34, 25, 12, 22, 11, 90]
    print("Original array:", arr)
    #print("Bubble Sort:", bubble_sort(arr.copy()))
    print("Insertion Sort:", insertion_sort(arr.copy()))
    print("Merge Sort:", merge_sort(arr.copy()))
    print("Quick Sort:", quick_sort(arr.copy()))

    # Linked List example
    ll = LinkedList()
    ll.insert(3)
    ll.insert(2)
    ll.insert(1)
    print("Linked List after insertion:")
    ll.traverse()
    ll.delete(2)
    print("Linked List after deletion of 2:")
    ll.traverse()

    # Stack example
    stack = Stack()
    stack.push(1)
    stack.push(2)
    stack.push(3)
    print("Stack size:", stack.size())
    print("Stack top element:", stack.peek())
    print("Popped element:", stack.pop())
    print("Stack size after pop:", stack.size())

    # Queue example
    queue = Queue()
    queue.enqueue(1)
    queue.enqueue(2)
    queue.enqueue(3)
    print("Queue size:", queue.size())
    print("Dequeued element:", queue.dequeue())
    print("Queue size after dequeue:", queue.size())


Original array: [64, 34, 25, 12, 22, 11, 90]
Insertion Sort: [11, 12, 22, 25, 34, 64, 90]
Merge Sort: [11, 12, 22, 25, 34, 64, 90]
Quick Sort: [11, 12, 22, 25, 34, 64, 90]
Linked List after insertion:
1 2 3 
Linked List after deletion of 2:
1 3 
Stack size: 3
Stack top element: 3
Popped element: 3
Stack size after pop: 2
Queue size: 3
Dequeued element: 1
Queue size after dequeue: 2


# Turtle 

In [9]:
import turtle

# Function to draw a square
def draw_square(size, color):
    turtle.color(color)
    for _ in range(4):
        turtle.forward(size)
        turtle.right(90)

# Function to draw a triangle
def draw_triangle(size, color):
    turtle.color(color)
    for _ in range(3):
        turtle.forward(size)
        turtle.right(120)

# Function to draw a circle
def draw_circle(radius, color):
    turtle.color(color)
    turtle.circle(radius)

# Function to clear the screen
def clear_screen():
    turtle.clear()

# Main function to get user inputs and draw shapes
def main():
    # Set up the turtle
    turtle.speed(1)

    while True:
        shape = input("Enter the shape to draw (square/triangle/circle) or 'clear' to reset: ").strip().lower()
        if shape == "clear":
            clear_screen()
            continue
        
        if shape not in ["square", "triangle", "circle"]:
            print("Invalid shape! Please enter 'square', 'triangle', 'circle', or 'clear'.")
            continue

        size = int(input("Enter the size of the shape: "))
        color = input("Enter the color of the shape: ").strip().lower()

        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()

        if shape == "square":
            draw_square(size, color)
        elif shape == "triangle":
            draw_triangle(size, color)
        elif shape == "circle":
            draw_circle(size, color)

# Run the main function
if __name__ == "__main__":
    main()
    turtle.done()


Enter the shape to draw (square/triangle/circle) or 'clear' to reset: circle
Enter the size of the shape: 100
Enter the color of the shape: red


KeyboardInterrupt: Interrupted by user

In [10]:
import turtle

# Function to draw a square
def draw_square(size, color):
    turtle.color(color)
    for _ in range(4):
        turtle.forward(size)
        turtle.right(90)

# Function to draw a triangle
def draw_triangle(size, color):
    turtle.color(color)
    for _ in range(3):
        turtle.forward(size)
        turtle.right(120)

# Function to draw a circle
def draw_circle(radius, color):
    turtle.color(color)
    turtle.circle(radius)

# Function to clear the screen
def clear_screen():
    turtle.clear()

# Main function to get user inputs and draw shapes
def main():
    # Set up the turtle
    turtle.speed(1)
    turtle.hideturtle()

    while True:
        shape = input("Enter the shape to draw (square/triangle/circle) or 'clear' to reset (or 'exit' to quit): ").strip().lower()
        if shape == "exit":
            break
        if shape == "clear":
            clear_screen()
            continue

        if shape not in ["square", "triangle", "circle"]:
            print("Invalid shape! Please enter 'square', 'triangle', 'circle', 'clear', or 'exit'.")
            continue

        size = int(input("Enter the size of the shape: "))
        color = input("Enter the color of the shape: ").strip().lower()

        turtle.penup()
        turtle.goto(0, 0)
        turtle.pendown()

        if shape == "square":
            draw_square(size, color)
        elif shape == "triangle":
            draw_triangle(size, color)
        elif shape == "circle":
            draw_circle(size, color)

    # Close the turtle graphics window
    turtle.bye()

# Run the main function
if __name__ == "__main__":
    main()


Enter the shape to draw (square/triangle/circle) or 'clear' to reset (or 'exit' to quit): circle
Enter the size of the shape: 100
Enter the color of the shape: red
Enter the shape to draw (square/triangle/circle) or 'clear' to reset (or 'exit' to quit): square
Enter the size of the shape: 200
Enter the color of the shape: blue
Enter the shape to draw (square/triangle/circle) or 'clear' to reset (or 'exit' to quit): triangle
Enter the size of the shape: 100
Enter the color of the shape: green
Enter the shape to draw (square/triangle/circle) or 'clear' to reset (or 'exit' to quit): quit
Invalid shape! Please enter 'square', 'triangle', 'circle', 'clear', or 'exit'.
Enter the shape to draw (square/triangle/circle) or 'clear' to reset (or 'exit' to quit): clear
Enter the shape to draw (square/triangle/circle) or 'clear' to reset (or 'exit' to quit): exit
